import Head from "next/head";
import Hero from "@/app/components/hero/Hero";
import LatestProp from "@/app/components/property/LatestProp";
import LuxuryProp from "@/app/components/property/LaxuryProp";
import { getProperties } from "@/lib/actions/property.action";
import ContactSection from "@/app/components/contact/ContactSection";
import Container from "@/app/components/container/Container";
import ServicesContainer from "@/app/components/services/ServicesContainer";
import PartnerCarousel from "@/app/components/PartnerCarousel";
import { groq } from "next-sanity";
import { client } from "@/lib/sanityLip/createClient";
import TestimonialContainer from "@/app/components/testimonial/TestimonialContainer";
import { getAllAreas } from '@/lib/actions/area.action';
import AreaHomeContainer from "@/app/components/area/AreaHomeContainer";
import BlogHome from "@/app/components/blog/BlogHome";
import {  TitleText } from '@/app/styles/CustomTexts';
import { getProjects } from "@/lib/actions/project.action";


const query = groq`*[_type == 'post']{
  ...,
  author->,
  categories[]->
} | order(_createdAt asc)`;

const Page = async () => {
  const properties = await getProperties();
  const projects = await getProjects();
  const plainProperties = properties.properties.map(property => property.toObject ? property.toObject() : property);
  const plainProjects = projects.projects.map(project => project.toObject ? project.toObject() : project);

  const posts = await client.fetch(query);
  const areasResult = await getAllAreas();
  
  const plainAreas = areasResult.areas.map((property: { toObject: () => any; }) =>
    property.toObject ? property.toObject() : property
  );
  
  // Assuming you want to display the name of the first project in Hero
const featuredProject = plainProjects.length > 0 ? plainProjects[0] : null;


  return (
    <>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero 
        projectName={featuredProject ? featuredProject.projectName : "Default Project Name"} 
        totalProjects={plainProjects.length} 
      />
      <div className="dark:bg-bgDark">
        <Container>
          <div className="flex flex-col items-center mb-10">
          <TitleText title="see how our realtors can help you" textStyles="text-center" />
          <ServicesContainer/>
            <LatestProp initialProperties={plainProperties} intialProjects={plainProjects} />
          </div>
            <PartnerCarousel/>
          <div className="space-y-10">
            <div className="bg-[#F9F9F9]">
              <LuxuryProp initialProperties={plainProperties} />
            </div>
            <ContactSection />
          </div>
          <BlogHome posts={posts} />

          <TestimonialContainer/>

          <AreaHomeContainer areas={plainAreas} />

          

        </Container>
      </div>
    </>
  );
};

export default Page;
